name: MCTrails
version: "1.0-SNAPSHOT"
author: Jacob Wysko
main: org.wysko.mctrails.Main
website: www.wysko.org
api-version: "1.15"
commands:
  trails:
    description: Displays configuration options for trails
    usage: §e/trails
    permission: mctrails.managePersonalTrail
    permission-message: You do not have the ability to manage your own trail.
    aliases:
      - trail
      - trailoreenos