name: MCTrails
version: 1.0
author: Jacob Wysko
main: org.wysko.mctrails.Main
website: www.wysko.org
api-version: 1.15
commands:
  toggletrail:
    description: Toggles trails on and off
    usage: §e/toggle
    permission: mctrails.managePersonalTrail
  testparticle:
    description: Tests particle display
    usage: §e/testparticle
    permission: mctrails.test
  defaulttrail:
    description: Sets the player's trail to the default
    usage: §e/defaulttrail
    permission: mctrails.test